### ISSUE TITLE
Add modal to frontend when clicking reference link and show chunk text

### ISSUE THREAD

**Issue by eherra** [asianomainen/rag-a-tag#14]
Let's create a modal which shows the content of the chunk.

Chunk content will be in the references list which is given from backend. 

References list has a new key value "content" added.

**Comment by Le36** [comment]
I appreciate the idea of utilizing a modal to display the chunk content, but I'd like to propose a CLI-based approach for consistency with the existing UX patterns. Could we implement a feature where users can issue a command after the prompt to select and view the content of any reference directly in the terminal window? This could enhance the uniformity of the interface and streamline the user experience, keeping all interactions within the terminal.
